<?php
/**
 * @file
 * monograph_pages.features.inc
 */

/**
 * Implementation of hook_node_info().
 */
function monograph_pages_node_info() {
  $items = array(
    'page' => array(
      'name' => t('Basic page'),
      'base' => 'node_content',
      'description' => t('Use <em>basic pages</em> for your static content, such as an \'About us\' page.'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  return $items;
}
